/** Unified flashcards + multi-mode study */
class FlashcardsModule {
  constructor(){
    this.STORAGE_KEY='student-helper-flashcards';
    this.statsKey='student-helper-stats';
    this.modes={TYPING_OF_THE_DEAD:'Typing of the Dead',OREGON_TRAIL:'Oregon Trail',MATCH_PAIRS:'Match Pairs'};
    this.sets=this.loadSets();
  }
  makeId(p){return `${p}-${Date.now()}-${Math.floor(Math.random()*1e6)}`;}
  escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  loadSets(){const s=storage.get(this.STORAGE_KEY);return Array.isArray(s)?s.map(x=>this.normalizeSet(x)):[];}
  normalizeSet(set){
    const cards=(Array.isArray(set.cards)?set.cards:[]).map(c=>this.normalizeCard(c,set.courseId||'general'));
    const metrics=set.metrics&&typeof set.metrics==='object'?set.metrics:{};
    return {id:set.id||this.makeId('set'),name:Validators.sanitizeInput(set.name||'Untitled Set'),courseId:Validators.sanitizeInput(set.courseId||'general'),preferredMode:set.preferredMode||'TYPING_OF_THE_DEAD',cards,createdAt:set.createdAt||new Date().toISOString(),metrics:{sessions:Number(metrics.sessions||0),perCardResults:this.normalizePerCard(metrics.perCardResults||{})}};
  }
  normalizePerCard(raw){const out={};Object.entries(raw||{}).forEach(([id,v])=>{out[String(id)]={attempts:Number(v&&v.attempts)||0,correct:Number(v&&v.correct)||0,lastResult:(v&&v.lastResult)||'INCORRECT'};});return out;}
  normalizeCard(card,fallbackCourse='general'){
    const tags=Array.isArray(card.tags)?card.tags.map(t=>Validators.sanitizeInput(String(t||'').trim())).filter(Boolean):[];
    const md=card.metadata&&typeof card.metadata==='object'?card.metadata:{};
    const keyPhrases=Array.isArray(md.keyPhrases)?md.keyPhrases.map(x=>Validators.sanitizeInput(String(x||'').trim())).filter(Boolean):[];
    const altAnswers=Array.isArray(md.altAnswers)?md.altAnswers.map(x=>Validators.sanitizeInput(String(x||'').trim())).filter(Boolean):[];
    return {id:String(card.id||this.makeId('card')),front:Validators.sanitizeInput(card.front||card.question||''),back:Validators.sanitizeInput(card.back||card.answer||''),tags,courseId:Validators.sanitizeInput(card.courseId||fallbackCourse),metadata:{keyPhrases,altAnswers},lastReviewed:card.lastReviewed||null,timesReviewed:Number.isFinite(card.timesReviewed)?card.timesReviewed:0,mastered:Boolean(card.mastered)};
  }
  saveSets(){storage.set(this.STORAGE_KEY,this.sets);this.updateStats();}
  createSet(name,courseId='general'){
    Validators.validateFlashcardSet(name);
    const set={id:this.makeId('set'),name:Validators.sanitizeInput(name),courseId:Validators.sanitizeInput(courseId||'general'),preferredMode:'TYPING_OF_THE_DEAD',cards:[],createdAt:new Date().toISOString(),metrics:{sessions:0,perCardResults:{}}};
    this.sets.push(set);this.saveSets();return set;
  }
  getSet(id){return this.sets.find(s=>String(s.id)===String(id));}
  deleteSet(id){this.sets=this.sets.filter(s=>String(s.id)!==String(id));this.saveSets();}
  addCard(setId,payload){
    const set=this.getSet(setId);if(!set)throw new Error('Set not found');
    Validators.validateTextInput(payload.front,1,5000);Validators.validateTextInput(payload.back,1,5000);
    const split=(v)=>String(v||'').split(',').map(x=>Validators.sanitizeInput(x.trim())).filter(Boolean);
    const card={id:this.makeId('card'),front:Validators.sanitizeInput(payload.front),back:Validators.sanitizeInput(payload.back),tags:split(payload.tags),courseId:set.courseId,metadata:{altAnswers:split(payload.altAnswers),keyPhrases:split(payload.keyPhrases)},lastReviewed:null,timesReviewed:0,mastered:false};
    set.cards.push(card);this.saveSets();return card;
  }
  removeCard(setId,cardId){const set=this.getSet(setId);if(!set)throw new Error('Set not found');set.cards=set.cards.filter(c=>String(c.id)!==String(cardId));delete set.metrics.perCardResults[String(cardId)];this.saveSets();}
  shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  normalizeTokens(t){return String(t||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(Boolean);}
  keywordScore(user,card){const u=new Set(this.normalizeTokens(user));const ans=new Set([...this.normalizeTokens(card.back),...(card.metadata?.altAnswers||[]).flatMap(x=>this.normalizeTokens(x)),...(card.metadata?.keyPhrases||[]).flatMap(x=>this.normalizeTokens(x))]);let o=0;ans.forEach(t=>{if(u.has(t))o++;});return o/Math.max(1,ans.size);}
  levenshtein(a,b){const x=String(a||'');const y=String(b||'');if(x===y)return 0;if(!x.length)return y.length;if(!y.length)return x.length;const m=Array(y.length+1).fill(null).map(()=>Array(x.length+1).fill(0));for(let i=0;i<=y.length;i++)m[i][0]=i;for(let j=0;j<=x.length;j++)m[0][j]=j;for(let i=1;i<=y.length;i++){for(let j=1;j<=x.length;j++){const c=y[i-1]===x[j-1]?0:1;m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+c);}}return m[y.length][x.length];}
  stringSim(a,b){const l=String(a||'').toLowerCase().trim();const r=String(b||'').toLowerCase().trim();const d=this.levenshtein(l,r);return 1-(d/(Math.max(l.length,r.length)||1));}
  fuzzyCheck(card,user){const kw=this.keywordScore(user,card);const sim=this.stringSim(user,card.back);if(kw>0.7||sim>0.85)return 'CORRECT';if(kw>0.4||sim>0.65)return 'PARTIAL';return 'INCORRECT';}
  buildSession(set,mode){return {id:this.makeId('session'),mode,courseId:set.courseId,cardQueue:this.shuffle(set.cards.map(c=>c.id)),stats:{correct:0,partial:0,incorrect:0},perCardResults:{}};}
  recordResult(set,session,card,result){
    const id=String(card.id);const sr=session.perCardResults[id]||{attempts:0,correct:0,lastResult:'INCORRECT'};sr.attempts+=1;if(result==='CORRECT'){sr.correct+=1;session.stats.correct+=1;}else if(result==='PARTIAL'){session.stats.partial+=1;}else{session.stats.incorrect+=1;}sr.lastResult=result;session.perCardResults[id]=sr;
    const pr=set.metrics.perCardResults[id]||{attempts:0,correct:0,lastResult:'INCORRECT'};pr.attempts+=1;if(result==='CORRECT')pr.correct+=1;pr.lastResult=result;set.metrics.perCardResults[id]=pr;
    card.timesReviewed=(card.timesReviewed||0)+1;card.lastReviewed=new Date().toISOString();card.mastered=pr.attempts>0&&(pr.correct/pr.attempts)>=0.75;
  }
  computeCardMastery(per){return Object.entries(per||{}).map(([cardId,r])=>({cardId,attempts:Number(r.attempts||0),correct:Number(r.correct||0),masteryScore:r.attempts?(r.correct/r.attempts):0}));}
  computeCourseUnderstanding(cards,mastery,courseId){const by=new Map(mastery.map(m=>[String(m.cardId),m]));const c=cards.filter(x=>String(x.courseId)===String(courseId));const s=c.map(x=>by.get(String(x.id))?.masteryScore||0);const avg=s.reduce((a,b)=>a+b,0)/Math.max(1,s.length);return {courseId,avgMastery:avg,weakCards:c.filter(x=>(by.get(String(x.id))?.masteryScore||0)<0.4).map(x=>x.id)};}
  computeTagUnderstanding(cards,mastery){const by=new Map(mastery.map(m=>[String(m.cardId),m]));const map={};cards.forEach(c=>{const sc=by.get(String(c.id))?.masteryScore||0;const tags=(Array.isArray(c.tags)&&c.tags.length)?c.tags:['untagged'];tags.forEach(t=>{if(!map[t])map[t]=[];map[t].push(sc);});});return Object.entries(map).map(([tag,s])=>({tag,avg:s.reduce((a,b)=>a+b,0)/Math.max(1,s.length)})).sort((a,b)=>a.avg-b.avg);}
  calculateMasteryPercent(set){if(!set.cards.length)return 0;const m=this.computeCardMastery(set.metrics.perCardResults);const c=this.computeCourseUnderstanding(set.cards,m,set.courseId);return Math.round(c.avgMastery*100);}
  renderSets(){
    const container=document.getElementById('flashcard-sets');if(!container)return;
    if(!this.sets.length){container.innerHTML='<p class="text-muted">No flashcard sets yet. Create one to get started!</p>';return;}
    container.innerHTML=this.sets.map((set)=>{
      const mastery=this.calculateMasteryPercent(set);
      const weakTags=this.computeTagUnderstanding(set.cards,this.computeCardMastery(set.metrics.perCardResults)).filter(x=>x.avg<0.5).slice(0,3).map(x=>`${this.escapeHtml(x.tag)} (${Math.round(x.avg*100)}%)`).join(', ');
      const cards=set.cards.map((card)=>{const r=set.metrics.perCardResults[String(card.id)]||{attempts:0,correct:0};const pct=r.attempts?Math.round((r.correct/r.attempts)*100):0;return `<div style="display:flex;justify-content:space-between;gap:.5rem;padding:.6rem;border:1px solid var(--border);border-radius:8px;background:var(--bg-primary);margin-bottom:.5rem;"><div><div style="font-weight:700">${this.escapeHtml(card.front)}</div><div>${this.escapeHtml(card.back)}</div><div style="font-size:.8rem;color:var(--text-secondary)">Tags: ${this.escapeHtml((card.tags||[]).join(', ')||'none')} | Mastery: ${pct}%</div></div><button class="btn btn-secondary btn-small" data-action="remove-card" data-set-id="${set.id}" data-card-id="${card.id}">Remove</button></div>`;}).join('')||'<p class="text-muted">No cards yet.</p>';
      return `<div class="card"><div style="display:flex;justify-content:space-between;gap:.6rem;flex-wrap:wrap;align-items:center;"><div><h4 style="margin:0">${this.escapeHtml(set.name)}</h4><div class="text-muted" style="font-size:.9rem;">Course: ${this.escapeHtml(set.courseId)} | ${set.cards.length} cards</div></div><div style="display:flex;gap:.4rem;flex-wrap:wrap;"><select class="form-control" data-action="mode-select" data-set-id="${set.id}" style="min-width:180px;">${Object.entries(this.modes).map(([k,l])=>`<option value="${k}" ${set.preferredMode===k?'selected':''}>${this.escapeHtml(l)}</option>`).join('')}</select><button class="btn btn-primary btn-small" data-action="study-set" data-set-id="${set.id}">Study</button><button class="btn btn-secondary btn-small" data-action="delete-set" data-set-id="${set.id}">Delete</button></div></div><div style="background:var(--primary-lighter);padding:.6rem;border-radius:8px;margin:1rem 0;"><div style="font-size:.85rem;color:var(--text-secondary);">Course understanding: ${mastery}%</div><div style="font-size:.82rem;color:var(--text-secondary);">Weak tags: ${weakTags||'none yet'}</div></div>${cards}<div data-set-form="${set.id}" style="border-top:1px solid var(--border);padding-top:.8rem;"><input class="form-control" data-field="front" placeholder="Front" style="margin-bottom:.5rem;"><textarea class="form-control" rows="2" data-field="back" placeholder="Back" style="margin-bottom:.5rem;"></textarea><input class="form-control" data-field="tags" placeholder="Tags (comma)" style="margin-bottom:.5rem;"><input class="form-control" data-field="altAnswers" placeholder="Alt answers (comma)" style="margin-bottom:.5rem;"><input class="form-control" data-field="keyPhrases" placeholder="Key phrases (comma)" style="margin-bottom:.5rem;"><button class="btn btn-secondary btn-small" data-action="add-card" data-set-id="${set.id}">+ Add Card</button></div></div>`;
    }).join('');
    this.attachSetListeners(container);
  }
  attachSetListeners(container){
    container.querySelectorAll('[data-action="delete-set"]').forEach(btn=>btn.addEventListener('click',()=>{this.deleteSet(btn.getAttribute('data-set-id'));this.renderSets();ErrorHandler.showNotification('Flashcard set deleted','info');}));
    container.querySelectorAll('[data-action="mode-select"]').forEach(sel=>sel.addEventListener('change',()=>{const set=this.getSet(sel.getAttribute('data-set-id'));if(!set)return;set.preferredMode=sel.value;this.saveSets();}));
    container.querySelectorAll('[data-action="add-card"]').forEach(btn=>btn.addEventListener('click',()=>{const setId=btn.getAttribute('data-set-id');const form=btn.closest('[data-set-form]');if(!form)return;const payload={front:(form.querySelector('[data-field="front"]')||{}).value||'',back:(form.querySelector('[data-field="back"]')||{}).value||'',tags:(form.querySelector('[data-field="tags"]')||{}).value||'',altAnswers:(form.querySelector('[data-field="altAnswers"]')||{}).value||'',keyPhrases:(form.querySelector('[data-field="keyPhrases"]')||{}).value||''};try{this.addCard(setId,payload);['front','back','tags','altAnswers','keyPhrases'].forEach(f=>{const el=form.querySelector(`[data-field="${f}"]`);if(el)el.value='';});this.renderSets();ErrorHandler.showNotification('Card added','success');}catch(e){ErrorHandler.showNotification(e.message,'error');}}));
    container.querySelectorAll('[data-action="remove-card"]').forEach(btn=>btn.addEventListener('click',()=>{try{this.removeCard(btn.getAttribute('data-set-id'),btn.getAttribute('data-card-id'));this.renderSets();ErrorHandler.showNotification('Card removed','info');}catch(e){ErrorHandler.showNotification(e.message,'error');}}));
    container.querySelectorAll('[data-action="study-set"]').forEach(btn=>btn.addEventListener('click',()=>this.studySet(btn.getAttribute('data-set-id'))));
  }
  studySet(setId){const set=this.getSet(setId);if(!set){ErrorHandler.showNotification('Set not found','error');return;}if(!set.cards.length){ErrorHandler.showNotification('Add cards before studying','error');return;}this.showStudyModal(set,set.preferredMode||'TYPING_OF_THE_DEAD');}
  createJourneyState(){return {position:0,food:10,health:10,wagonIntegrity:10,corruption:0,events:[]};}
  maybeTriggerRandomEvent(j){const n={...j,events:[...j.events]};if(Math.random()>=0.2)return n;const bad=n.corruption>=6?true:Math.random()<0.5;if(bad){const ev=[{d:'A wagon wheel breaks. -2 wagon integrity.',f:x=>x.wagonIntegrity=Math.max(0,x.wagonIntegrity-2)},{d:'A river crossing delays you. -3 progress.',f:x=>x.position=Math.max(0,x.position-3)}];const p=ev[Math.floor(Math.random()*ev.length)];p.f(n);n.events.push({id:this.makeId('event'),type:'BAD',description:p.d});}else{const ev=[{d:'You found wild berries. +3 food.',f:x=>x.food+=3},{d:'A scout guides you. +5 trail progress.',f:x=>x.position+=5}];const p=ev[Math.floor(Math.random()*ev.length)];p.f(n);n.events.push({id:this.makeId('event'),type:'GOOD',description:p.d});}return n;}
  applyAnswerToJourney(j,r){const n={...j,events:[...j.events]};if(r==='CORRECT'){n.position+=3;n.food+=1;n.corruption=Math.max(0,n.corruption-1);}else if(r==='PARTIAL'){n.position+=1;n.food=Math.max(0,n.food-1);}else{n.food=Math.max(0,n.food-2);n.health=Math.max(0,n.health-1);n.corruption+=2;}return this.maybeTriggerRandomEvent(n);}
  showStudyModal(set,mode){
    const session=this.buildSession(set,mode);let idx=0;let timer=null;let timeLeft=(mode==='OREGON_TRAIL'?20:15);let journey=this.createJourneyState();
    const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.7);display:flex;align-items:center;justify-content:center;padding:1rem;z-index:10000;';
    const modal=document.createElement('div');modal.style.cssText='background:var(--bg-secondary);color:var(--text-primary);width:min(820px,100%);max-height:90vh;overflow:auto;border-radius:14px;border:1px solid var(--border);box-shadow:var(--shadow-lg);padding:1.2rem;';
    const close=()=>{if(timer)clearInterval(timer);set.metrics.sessions+=1;this.saveSets();overlay.remove();this.renderSets();};
    const cardAt=(i)=>{const id=session.cardQueue[i];return set.cards.find(c=>String(c.id)===String(id));};
    const start=(onExpire)=>{if(timer)clearInterval(timer);timeLeft=(mode==='OREGON_TRAIL'?20:15);timer=setInterval(()=>{timeLeft-=1;const t=modal.querySelector('[data-timer]');if(t)t.textContent=String(Math.max(0,timeLeft));if(timeLeft<=0){clearInterval(timer);timer=null;onExpire();}},1000);};
    const finish=()=>{if(timer)clearInterval(timer);const total=session.stats.correct+session.stats.partial+session.stats.incorrect;const score=total?Math.round(((session.stats.correct+(session.stats.partial*0.5))/total)*100):0;const cm=this.computeCardMastery(set.metrics.perCardResults);const cu=this.computeCourseUnderstanding(set.cards,cm,set.courseId);modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:.5rem;"><h3 style="margin:0;">Session Complete</h3><button class="btn btn-secondary btn-small" data-close>Close</button></div><div class="card" style="margin-top:1rem;"><div><strong>Mode:</strong> ${this.escapeHtml(this.modes[mode]||mode)}</div><div><strong>Correct:</strong> ${session.stats.correct} | <strong>Partial:</strong> ${session.stats.partial} | <strong>Incorrect:</strong> ${session.stats.incorrect}</div><div><strong>Score:</strong> ${score}%</div><div><strong>Course understanding:</strong> ${Math.round(cu.avgMastery*100)}%</div><div><strong>Weak cards:</strong> ${cu.weakCards.length}</div></div>`;modal.querySelector('[data-close]').addEventListener('click',close);ErrorHandler.showNotification('Study session complete!','success');};
    const next=()=>{idx+=1;if(idx>=session.cardQueue.length){finish();return;}if(mode==='TYPING_OF_THE_DEAD')typing();else if(mode==='OREGON_TRAIL')trail();};
    const submit=(card,answer,forced)=>{const r=forced||this.fuzzyCheck(card,answer);this.recordResult(set,session,card,r);this.saveSets();return r;};
    const typing=()=>{const card=cardAt(idx);if(!card){finish();return;}modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:.5rem;"><h3 style="margin:0;">Typing of the Dead</h3><button class="btn btn-secondary btn-small" data-close>Close</button></div><div style="font-size:.9rem;color:var(--text-secondary);margin-top:.4rem;">Card ${idx+1}/${session.cardQueue.length}</div><div class="card" style="margin-top:1rem;"><div style="font-weight:700;">${this.escapeHtml(card.front)}</div><div style="margin:.5rem 0;">Time left: <strong data-timer>${timeLeft}</strong>s</div><textarea class="form-control" rows="3" data-answer placeholder="Type your answer"></textarea><div style="display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.6rem;"><button class="btn btn-primary" data-submit>Submit</button><button class="btn btn-secondary" data-skip>Skip</button></div><div data-feedback style="margin-top:.6rem;"></div></div>`;
      const answer=modal.querySelector('[data-answer]');const feedback=modal.querySelector('[data-feedback]');const handle=(f)=>{const r=submit(card,answer?answer.value.trim():'',f);if(feedback)feedback.innerHTML=`<strong>${r}</strong> | Answer: ${this.escapeHtml(card.back)}`;setTimeout(next,900);};
      modal.querySelector('[data-close]').addEventListener('click',close);modal.querySelector('[data-submit]').addEventListener('click',()=>handle());modal.querySelector('[data-skip]').addEventListener('click',()=>handle('INCORRECT'));if(answer){answer.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handle();}});answer.focus();}start(()=>handle('INCORRECT'));
    };
    const trail=()=>{const card=cardAt(idx);if(!card){finish();return;}const ev=journey.events.length?journey.events[journey.events.length-1]:null;modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:.5rem;"><h3 style="margin:0;">Oregon Trail Study</h3><button class="btn btn-secondary btn-small" data-close>Close</button></div><div style="font-size:.9rem;color:var(--text-secondary);margin-top:.4rem;">Card ${idx+1}/${session.cardQueue.length}</div><div class="card" style="margin-top:1rem;"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:.35rem;"><div><strong>Progress:</strong> ${Math.min(100,journey.position)}</div><div><strong>Food:</strong> ${journey.food}</div><div><strong>Health:</strong> ${journey.health}</div><div><strong>Wagon:</strong> ${journey.wagonIntegrity}</div><div><strong>Corruption:</strong> ${journey.corruption}</div><div>Time: <strong data-timer>${timeLeft}</strong>s</div></div>${ev?`<div style="margin-top:.5rem;font-size:.86rem;color:var(--text-secondary);">Event: ${this.escapeHtml(ev.description)}</div>`:''}<div style="margin-top:.6rem;font-weight:700;">${this.escapeHtml(card.front)}</div><textarea class="form-control" rows="3" data-answer placeholder="Type your answer"></textarea><div style="display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.6rem;"><button class="btn btn-primary" data-submit>Submit</button><button class="btn btn-secondary" data-skip>Skip</button></div><div data-feedback style="margin-top:.6rem;"></div></div>`;
      const answer=modal.querySelector('[data-answer]');const feedback=modal.querySelector('[data-feedback]');const handle=(f)=>{const r=submit(card,answer?answer.value.trim():'',f);journey=this.applyAnswerToJourney(journey,r);if(feedback)feedback.innerHTML=`<strong>${r}</strong> | Answer: ${this.escapeHtml(card.back)}`;if(journey.health<=0||journey.wagonIntegrity<=0||journey.position>=100){finish();return;}setTimeout(next,1000);};
      modal.querySelector('[data-close]').addEventListener('click',close);modal.querySelector('[data-submit]').addEventListener('click',()=>handle());modal.querySelector('[data-skip]').addEventListener('click',()=>handle('INCORRECT'));if(answer){answer.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handle();}});answer.focus();}start(()=>handle('INCORRECT'));
    };
    const match=()=>{const sample=this.shuffle(set.cards).slice(0,Math.min(6,set.cards.length));const left=sample.map(c=>({id:c.id,text:c.front}));const right=this.shuffle(sample).map(c=>({id:c.id,text:c.back}));const matched=new Set();let lSel=null;let rSel=null;const render=()=>{modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:.5rem;"><h3 style="margin:0;">Match Pairs</h3><button class="btn btn-secondary btn-small" data-close>Close</button></div><div style="font-size:.9rem;color:var(--text-secondary);margin-top:.4rem;">Matched: ${matched.size}/${left.length}</div><div class="card" style="margin-top:1rem;"><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;"><div>${left.map(it=>`<button class="btn btn-secondary" data-side="L" data-id="${it.id}" ${matched.has(it.id)?'disabled':''} style="display:block;width:100%;margin-bottom:.45rem;text-align:left;${lSel===it.id?'outline:2px solid var(--primary);':''}">${this.escapeHtml(it.text)}</button>`).join('')}</div><div>${right.map(it=>`<button class="btn btn-secondary" data-side="R" data-id="${it.id}" ${matched.has(it.id)?'disabled':''} style="display:block;width:100%;margin-bottom:.45rem;text-align:left;${rSel===it.id?'outline:2px solid var(--primary);':''}">${this.escapeHtml(it.text)}</button>`).join('')}</div></div><div data-feedback style="margin-top:.6rem;color:var(--text-secondary);"></div></div>`;modal.querySelector('[data-close]').addEventListener('click',close);modal.querySelectorAll('[data-side]').forEach(b=>b.addEventListener('click',()=>{const side=b.getAttribute('data-side');const id=b.getAttribute('data-id');if(!id||matched.has(id))return;if(side==='L')lSel=id;else rSel=id;if(lSel&&rSel){const card=set.cards.find(c=>String(c.id)===String(lSel));const fb=modal.querySelector('[data-feedback]');if(lSel===rSel){matched.add(lSel);if(card)this.recordResult(set,session,card,'CORRECT');if(fb)fb.textContent='Correct match.';}else{if(card)this.recordResult(set,session,card,'INCORRECT');if(fb)fb.textContent='Not a match.';}lSel=null;rSel=null;this.saveSets();if(matched.size>=left.length){finish();return;}}render();}));};render();};
    overlay.addEventListener('click',(e)=>{if(e.target===overlay)close();});document.body.appendChild(overlay);overlay.appendChild(modal);if(mode==='TYPING_OF_THE_DEAD')typing();else if(mode==='OREGON_TRAIL')trail();else match();
  }
  updateStats(){try{const s=storage.get(this.statsKey)||{notesCreated:0,grammarChecks:0,flashcards:0,classes:0};s.flashcards=this.sets.reduce((sum,set)=>sum+set.cards.length,0);storage.set(this.statsKey,s);window.dispatchEvent(new CustomEvent('stats-updated',{detail:s}));}catch(e){console.error('Failed to update stats:',e);}}
}
const flashcardsModule=new FlashcardsModule();window.flashcardsModule=flashcardsModule;
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',setupFlashcardListeners);}else{setupFlashcardListeners();}
function setupFlashcardListeners(){
  const createBtn=document.getElementById('create-flashcard-set-btn');
  const nameInput=document.getElementById('flashcard-set-name');
  const courseInput=document.getElementById('flashcard-course-id');
  const create=()=>{const name=nameInput?nameInput.value.trim():'';const course=courseInput?courseInput.value.trim():'general';if(!name){ErrorHandler.showNotification('Please enter a set name','error');return;}try{flashcardsModule.createSet(name,course||'general');flashcardsModule.renderSets();if(nameInput)nameInput.value='';ErrorHandler.showNotification('Flashcard set created!','success');}catch(e){ErrorHandler.showNotification(e.message,'error');}};
  if(createBtn)createBtn.addEventListener('click',create);
  if(nameInput)nameInput.addEventListener('keydown',(e)=>{if(e.key==='Enter')create();});
  flashcardsModule.renderSets();
}
